language: java

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Prevent Travis's default of: mvn install -DskipTests=true
install: ""

script:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Xmx1500m"
  - mvn clean integration-test
 